[package]
authors = ['Pontem Network Team <https://github.com/orgs/pontem-network/people>']
description = '🚀 Pontem Node with Move VM onboard'
repository = 'https://github.com/pontem-network/pontem/'
homepage = 'https://pontem.network'
license = 'Apache-2.0'
name = 'pontem-node'
edition = '2018'
build = 'build.rs'
version = '0.4.1'

[[bin]]
name = 'pontem'
path = 'src/main.rs'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
stdlib-fetch = { path = "../utils/stdlib-fetch" }

[dependencies]
async-io = "1.3"
futures = { version = "0.3.1", features = ["compat"] }
jsonrpc-core = '15.1.0'
serde_json = '1.0'
structopt = '0.3.8'
# TODO: update parity-scale-codec to 2.2.0
codec = { package = 'parity-scale-codec', version = '2.0.0' }
log = "0.4"
serde = { version = "1.0", features = ["derive"]}

# Substrate dependencies
frame-benchmarking = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
frame-benchmarking-cli = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
pallet-transaction-payment-rpc = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
substrate-frame-rpc-system = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
substrate-prometheus-endpoint = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }

# Substarte Client Dependencies
sc-basic-authorship = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-cli = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10', features = ['wasmtime'] }
sc-client-api = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-consensus = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-executor = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10', features = ['wasmtime'] }
sc-finality-grandpa = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-keystore = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-rpc = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-rpc-api = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-service = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10', features = ['wasmtime'] }
sc-telemetry = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-transaction-pool = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-tracing = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-chain-spec = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-network = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-transaction-pool-api = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sc-consensus-manual-seal = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }

# Substrate Primitive Dependencies
sp-api = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-block-builder = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-blockchain = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-consensus = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-core = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-finality-grandpa = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-inherents = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-runtime = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-transaction-pool = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-timestamp = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-session = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-offchain = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
sp-keystore = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.10' }
nimbus-primitives = { git = "https://github.com/purestake/cumulus", rev = "5053470650f19ab4f30e37b4a4f3cf292a8e8fe9" }

# Cumulus dependencies
cumulus-client-consensus-relay-chain = { git = "https://github.com/purestake/cumulus", rev = "5053470650f19ab4f30e37b4a4f3cf292a8e8fe9" }
cumulus-client-consensus-common = { git = "https://github.com/purestake/cumulus", rev = '5053470650f19ab4f30e37b4a4f3cf292a8e8fe9' }
cumulus-client-network = { git = 'https://github.com/purestake/cumulus', rev = '5053470650f19ab4f30e37b4a4f3cf292a8e8fe9' }
cumulus-client-service = { git = 'https://github.com/purestake/cumulus', rev = '5053470650f19ab4f30e37b4a4f3cf292a8e8fe9' }
cumulus-client-cli = { git = 'https://github.com/purestake/cumulus', rev = '5053470650f19ab4f30e37b4a4f3cf292a8e8fe9' }
cumulus-primitives-core = { git = 'https://github.com/purestake/cumulus', rev = '5053470650f19ab4f30e37b4a4f3cf292a8e8fe9' }
cumulus-primitives-parachain-inherent = { git = 'https://github.com/purestake/cumulus', rev = '5053470650f19ab4f30e37b4a4f3cf292a8e8fe9' }
nimbus-consensus = { git = "https://github.com/purestake/cumulus", rev = "5053470650f19ab4f30e37b4a4f3cf292a8e8fe9" }


# Polkadot dependencies
polkadot-primitives = { git = 'http://github.com/paritytech/polkadot.git', branch = 'release-v0.9.10' }
polkadot-service = { git = 'http://github.com/paritytech/polkadot.git', branch = 'release-v0.9.10' }
polkadot-parachain = { git = 'http://github.com/paritytech/polkadot.git', branch = 'release-v0.9.10' }

# Local dependencies
pontem-runtime = { path = '../runtime' }
sp-mvm-rpc = { path = '../pallets/sp-mvm/rpc' }
sp-mvm-rpc-runtime = { path = '../pallets/sp-mvm/rpc/runtime' }

# FIXME: You MUST set the relay chain networks you wish to target in the `features` here
# Options are found here: https://github.com/paritytech/polkadot/blob/master/cli/Cargo.toml#L64-L71
#
# Alternatively to setting here, you can use cargo CLI at build time:
# https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options
#
# ** Don't enable relay chains you don't need, as this is a **very** heavy build for no reason**
# More info: https://github.com/paritytech/polkadot/pull/3189
polkadot-cli = { git = 'http://github.com/paritytech/polkadot.git', branch = 'release-v0.9.10', features = ["rococo-native"] }

[dependencies.move-vm]
package = "mvm"
git = "https://github.com/pontem-network/sp-move-vm.git"
rev = "52ccf19823c9516d448ac6dc360b42dab4ac97d2"
default-features = false
features = [ "move_stdlib" ]

[features]
default = []
runtime-benchmarks = ['pontem-runtime/runtime-benchmarks', 'polkadot-service/runtime-benchmarks']
